org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
neo_version_range=[21.1.4,)
loader_version_range=[2,)

mod_id=celestial_overhaul
mod_name=Celestial Overhaul
mod_license=LGPL-2.1
mod_version=2.0.0b
mod_group_id=Xiaoyue
mod_authors=Xiaoyue
mod_description=Celestial Overhaul.

lljij = true
registrate_version = MC1.21-1.3.0+55
jei_minecraft_version = 1.21-neoforge
jei_version = 19.5.0.44
curios_version = 9.0.5+1.21